/*
 https://github.com/jawj/github-widget
Copyright (c) 2011 - 2012 George MacKerron
Released under the MIT licence: http://opensource.org/licenses/mit-license
*/
(function(){var q=[].indexOf||function(a){for(var b=0,d=this.length;b<d;b++)if(b in this&&this[b]===a)return b;return-1},u={}.hasOwnProperty;var v=function(a,b){var d,f;g({cls:"gw-clearer",prevSib:b});var e=b.getAttribute("data-user");var c=b.getAttribute("data-options");c="string"===typeof c?JSON.parse(c):{};var h=[(e+".github.com").toLowerCase(),(e+".github.io").toLowerCase()];var r=c.sortBy||"watchers";e=parseInt(c.limit)||Infinity;var m=0;var k=a.sort(function(a,b){return b[r]-a[r]});var n=[];
a=0;for(d=k.length;a<d;a++){var l=k[a];if(!(!c.forks&&l.fork||(f=l.name.toLowerCase(),0<=q.call(h,f)))&&l.description){if(m++===e)break;n.push(g({parent:b,cls:"gw-repo-outer",kids:[g({cls:"gw-repo",kids:[g({cls:"gw-title",kids:[g({tag:"ul",cls:"gw-stats",kids:[g({tag:"li",text:l.watchers,cls:"gw-watchers"}),g({tag:"li",text:l.forks,cls:"gw-forks"})]}),g({tag:"a",href:l.html_url,text:l.name,cls:"gw-name"})]}),null!=l.language?g({cls:"gw-lang",text:l.language}):void 0,g({cls:"gw-repo-desc",text:l.description})]})]}))}}return n};
var k=[];var t=function(a,b,d){return m({url:a,success:function(a){var e,c;k[d]=k[d].concat(a.data);if(c=a.meta.Link)for(a=0,e=c.length;a<e;a++){var f=c[a];if("next"===f[1].rel){t(f[0],b,d);return}}return v(k[d],b)}})};var n=function(a,b){var d,f;null==b&&(b={});var e={};var c=a.className.match(n.re);if(null!=c){var h=0;for(f=c.length;h<f;h++)a=c[h],e[a]=!0}b=null!=(d=b.has)?d.match(n.re):void 0;if(null!=b){d=0;for(c=b.length;d<c;d++)if(a=b[d],!e[a])return!1;return!0}return null};n.re=/\S+/g;var p=
function(a){var b,d,f,e;null==a&&(a={});var c=null!=(d=a.inside)?d:document;d=null!=(b=a.tag)?b:"*";if(null!=a.id)return c.getElementById(a.id);if((b=null!=a.cls)&&"*"===d&&null!=c.getElementsByClassName)return c.getElementsByClassName(a.cls);c=c.getElementsByTagName(d);if(b){var h;var g=[];var k=0;for(h=c.length;k<h;k++)b=c[k],n(b,{has:a.cls})&&g.push(b);c=g}return null==a.multi&&(f=d.toLowerCase(),0<=q.call(p.uniqueTags,f))?null!=(e=c[0])?e:null:c};p.uniqueTags="html body frameset head title base".split(" ");
var w=function(a){return document.createTextNode(""+a)};var g=function(a){var b,d,f;null==a&&(a={});var e=document.createElement(null!=(b=a.tag)?b:"div");for(d in a)if(u.call(a,d)){var c=a[d];switch(d){case "tag":continue;case "parent":c.appendChild(e);break;case "kids":var h=0;for(f=c.length;h<f;h++)b=c[h],null!=b&&e.appendChild(b);break;case "prevSib":c.parentNode.insertBefore(e,c.nextSibling);break;case "text":e.appendChild(w(c));break;case "cls":e.className=c;break;default:e[d]=c}}return e};var m=
function(a){var b,d;var f=null!=(b=a.callback)?b:"_JSONPCallback_"+m.callbackNum++;b=a.url.replace("<cb>",f);window[f]=null!=(d=a.success)?d:m.noop;return g({tag:"script",src:b,parent:p({tag:"head"})})};m.callbackNum=0;m.noop=function(){};(function(){var a,b;var d=p({tag:"div",cls:"github-widget"});var f=[];var e=a=0;for(b=d.length;a<b;e=++a){var c=d[e];f.push(function(a,b){k.push([]);return t("https://api.github.com/users/"+a.getAttribute("data-user")+"/starred?callback=<cb>",a,b)}(c,e))}console.log(f);
return f})()}).call(this);
